export { Home as PageHome } from "./Home"
export { Revenues as PageRevenues } from "./Revenues"
export { Login as PageLogin } from "./Login"
export { Register as PageRegister } from "./Register"
export { Layout as PageLayout } from "./Layout"
export { Kitchen as PageKitchen } from "./Kitchen"